### ISSUE TITLE
New fishing card icon 

### ISSUE THREAD

**Issue by thomasivarlden** [ifiske/iFiske#111]
Replace credit-card icon, with a fishing card icon

**Comment by Maistho** [comment]
Ikonen är lite misaligned med andra ikoner i storlek/bredd/margins? Behöver kollas lite mer på.

**Comment by thomasivarlden** [comment]
Tycker inte misalign gör så mycket, det kan vara ok.
Däremot används den inte överallt, t.ex. om man går in i en länsvy, eller i nedre tabben på ett område; där är det fortfarande gamla kreditskortsikonen.
