### ISSUE TITLE
Organisations to administer doesn't change

### ISSUE THREAD

**Issue by thomasivarlden** [ifiske/iFiske#129]
If I, at server side, changes what organisation the user is a manger for, this is not mirrored in the app.

I went to server side, and removed administration rights for one organisation, adding another one.

I've tried to log in and out, and to update the database, still, the original organisations I had access to in the beginning remains in the drop-down list, and the new one isn't there.

**Comment by thomasivarlden** [comment]
Whoa... After a while, using the view (not exiting the app, nor logging in our out), the new organisation suddenly was available to me! Cache issues?

**Comment by Maistho** [comment]
Probably. I'll try disabling the cache for those api calls
