### ISSUE TITLE
Empty drop down box in administration view

### ISSUE THREAD

**Issue by thomasivarlden** [ifiske/iFiske#130]
The drop down is empty or looks empty. (Tapping it reveals the options though)

See image.

![img_0858](https://cloud.githubusercontent.com/assets/6755937/22332913/9b3af7a6-e3d3-11e6-9888-728bdc21ce41.png)
![img_0857](https://cloud.githubusercontent.com/assets/6755937/22332914/9b40af70-e3d3-11e6-8d57-bc3acd9ad52d.png)

**Comment by Maistho** [comment]
Kan inte reproducera den här buggen längre. Något speciellt du gjorde för att få den att uppstå?
