### ISSUE TITLE
Camera QR "Cancel" button in english

### ISSUE THREAD

**Issue by thomasivarlden** [ifiske/iFiske#131]
When using the app in Swedish mode, the button to cancel a QR code scan says "Cancel" and not "Avbryt"

**Comment by Maistho** [comment]
På Android är det att bli samma språk som telefonen kör, på ios är det
alltid engelska. Ska se om det finns något bra sätt att lösa det på

**Comment by thomasivarlden** [comment]
Lägg inte mycket tid på det. Ganska oväsentligt.

**Comment by Maistho** [comment]
wontfix
