### ISSUE TITLE
Can't access server

### ISSUE THREAD

**Issue by lemonandlime** [ifiske/iFiske#133]
No data available on iOS. Probably server issue. Create account is working but no other data is awaliable. Tried this same time as the I'm filing this bug.

**Comment by Maistho** [comment]
We've had no known server downtime during the day, so it's probably either a connectivity issue or an issue with the app. Can you still reproduce it now?

**Comment by lemonandlime** [comment]
No I don't get that issue anymore. I'm now on a much better network. But I had a ok connection when the issue occurred. I could create an account so it was not that. The only thing I can think of is that I was in another in another municipality when the bug occurred or that my internet was to slow so the main information could not be downloaded and failed silently. All the icons on the main page was gray.

**Comment by Maistho** [comment]
I guess it could've been a temporary issue that we didn't know about.

Good thing it works now at least, I'll keep an eye out for similar problems in the future.
