### ISSUE TITLE
Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by thomasivarlden** [ifiske/iFiske#80]
Missing Push Notification Entitlement - The app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

**Comment by Maistho** [comment]
Det är tydligen en plugin som skapar det här problemet. Vi kan byta provisioning profile när vi ska använda notifications.
Appen går genom review ändå?

**Comment by thomasivarlden** [comment]
Troligen

onsdag 20 maj 2015 skrev Gustav Bylund <notifications@github.com>:

**Comment by Maistho** [comment]
Då kollar vi på det här igen när push notifieringar faktiskt är med i appen.
