### ISSUE TITLE
Swedish characters on older Androids

### ISSUE THREAD

**Issue by thomasivarlden** [ifiske/iFiske#84]
Searching for "Linköping" on the main search in the app, results in a search for "linkping" without the "ö"
Probably due to the platform being an older phone? In this case it is a Samsung galaxy S2 running Android v 2.3.5.

**Comment by Maistho** [comment]
I'll look into the possible causes for this.
Do we support devices that old?

**Comment by thomasivarlden** [comment]
I guess Ice Cream and forward is enough to support. Does phonegap support any flags for this?

**Comment by Maistho** [comment]
Yes, you can set the sdkversion with a flag.
